### ISSUE TITLE
Fix creation of intial Django superuser account

### ISSUE THREAD

**Issue by hardfalcon** [rdmorganiser/rdmo-ansible#3]
* [x] Fix creation of intial Django superuser account. This seems to fail mainly because ansible refuses (for unknown reasons) to accept the value `True` returned in https://github.com/rdmorganiser/rdmo-ansible/blob/main/roles/rdmo-venv/tasks/configure-rdmo.yml#L39 as an actual boolean `True`, and thus sets the `superuser_missing` variable to `False`, which prevents the subsequent task from actually creating the Django superuser.

* [x]  We will also need a way to set a randomly generated password for this account and show that password to the person executing the ansible playbook without having the password logged.

**Comment by jmfrenzel** [comment]
Solved by: https://github.com/rdmorganiser/rdmo-ansible/commit/76f6ffcd681e3f2dcc942aa4f611232b1c13bce3

**Comment by jmfrenzel** [comment]
Fixed through 6c6bda2d5f7c0776fafb6945f9857a9343eb3f49
