### ISSUE TITLE
Get rid of all hardcoded passwords

### ISSUE THREAD

**Issue by hardfalcon** [rdmorganiser/rdmo-ansible#4]
All hardcoded passwords need to be replaced with secure, randomly generated passwords. We will also need a way to supply existing passwords to allow running this ansible playbook on existing deployments.
- [x] PostgreSQL
- [x] django superuser

**Comment by jmfrenzel** [comment]
Solved: https://github.com/rdmorganiser/rdmo-ansible/commit/76f6ffcd681e3f2dcc942aa4f611232b1c13bce3

Solved: https://github.com/rdmorganiser/rdmo-ansible/commit/ead1cb238a7c9046ba5d30b323bcdd2bd1b40891

**Comment by hardfalcon** [comment]
Fixed through 5bda9d87ddfda41095103d7e6a99a7bf4551e332 and 6c6bda2d5f7c0776fafb6945f9857a9343eb3f49.
